public enum TokenType {

    BEGIN_STREAM,
    END_STREAM,

    L_PAREN,
    R_PAREN,

    IDENTIFIER,
    INTEGER,
    BOOL_TRUE,
    BOOL_FALSE,

    OPERATOR_PLUS,
    OPERATOR_MINUS,
    OPERATOR_MULTIPLY,
    OPERATOR_DIVIDE,
    OPERATOR_EQUALS,
    OPERATOR_LESS,
    OPERATOR_GREATER,
    OPERATOR_LESSEQUALS,
    OPERATOR_GREATEREQUALS,

    SPECIAL_IF,
    SPECIAL_ELSE,
    SPECIAL_COND,
    SPECIAL_LET,
    SPECIAL_LAMBDA,
    SPECIAL_DEFINE
}